webapp/cinemas/cinemas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^predict/', include('predict.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

webapp/cinemas/predict/urls.py
from django.conf.urls import url

from . import views

app_name = 'predict'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/results/
    url(r'^results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^make_predict/$', views.make_prediction, name='make_prediction'),
]

webapp/cinemas/predict/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

webapp/cinemas/predict/forms.py
from django import forms


class UploadFileForm(forms.Form):

    csv_file = forms.FileField(label='Select file for import')

webapp/cinemas/predict/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .forms import UploadFileForm
from django.conf import settings
import os
from .prediction_func import cinemas_predict
import pandas as pd
import os, random, string



# Create your views here.
def index(request):
    return render(request, 'predict/index.html')

def results(request):
    response = "You're looking at the results of prediction."
    return HttpResponse(response)

def make_prediction(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():

            name_path, file_name = handle_uploaded_file(request.FILES['csv_file'])
            result, df = cinemas_predict(name_path)
            os.remove(name_path)
            if result: return HttpResponse("Error...")

            df.sort_index(inplace = True)

            result_file = os.path.join(settings.MEDIA_ROOT, file_name)
            df.to_csv(result_file)
            result_file_url = settings.MEDIA_URL + file_name

            context = {'data': [(key,value) for key,value in zip(df.index, df)],'result_file': result_file_url}



            return render(request, 'predict/results.html', context)

            #return HttpResponseRedirect('/predict/results/')
        else:
            return HttpResponse("Error...")

def handle_uploaded_file(f):
    file_name = f.name

    length = 13
    chars = string.ascii_letters + string.digits + '!@$^&*'
    random.seed = (os.urandom(1024))
    a = ''.join(random.choice(chars) for i in range(length))

    file_name, exts = os.path.splitext(file_name)
    file_name = '%s%s%s' % (file_name,str(a), exts)

    name_path = os.path.join(settings.TEMP_DIR, file_name)
    with open(name_path, 'wb') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    return name_path, file_name

webapp/cinemas/predict/templates/predict/base.html
 <html>
 <head>
 <metacharset="UTF-8"/>
 <title>Visitors cinema prediction</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
 <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
 </head>
<body bg>
<div class="container">

  {%block content %}{% endblock content %}


  <!--Start Footer-->
 <div class="row" id="footer" style = "border-top:1px solid #dddddd;">
  &copy; 2017 Kyivstar BigData School
 </div>
 <!--End Footer-->



</div>
</body>
</html>

webapp/cinemas/predict/templates/predict/index.html
{%extends "predict/base.html" %}

{%block content %}

  <h2>Please select the .csv file with user ids</h2>
    <div class="jumbotron">
      <form action = "{% url 'predict:make_prediction' %}" method = "post" enctype="multipart/form-data">
      {% csrf_token %}

      <input class=" btn btn-sm form-control" id="id_csv_file" name="csv_file" type="file">
      <p><p><button class="btn btn-primary btn-lg" type="submit" data-loading-text="Завантаження...">Завантажити</button>

    </form>
  </div>

{%endblock content %}

webapp/cinemas/predict/templates/predict/results.html
{%extends "predict/base.html" %}

{%block content %}
<div class = "header">
  <h2>Prediction results</h2>
</div>
<div class="row">
      <a href ="{{result_file}}">Download as .csv file</a> &nbsp; &nbsp; &nbsp; &nbsp;<a href = "{% url 'predict:index' %}">Make another prediction</a>
</div>

    <br><br>
      <table style="text-align: center;">
      <tr>
        <th>SUBS_KEY&nbsp;</th>
        <th>Prediction</th>
     </tr>

      {% for key, value in data %}
          <tr>
              <td> {{ key }} </td> <td> {{ value }} </td>
          </tr>
      {% endfor %}
      </table>


{%endblock content %}